export { socialConfigs } from "./model";
export { contacts, confidantial } from "./model";
export { ticketPrice } from "./model";
export { benefits, type Benefit } from "./model";
export { opportunities } from "./model";
export { partners, type Partner } from "./model";
export { bangles, type Bangle } from "./model";
export { premiumCapabilities, type Capability } from "./model";
export { premiumSales, type PremiumSale } from "./model";
export { Rules, RulesValues, type RuleText } from "./model";
export type { SocialConfig, SocialPlatform } from "./model";
